name: Deploy snapshot to clojars

on:
  push:
    branches:
      - main

jobs:
  deploy-clojars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          lein: 2.9.6

      - name: Generate pom.xml
        run: lein install

      - name: Deploy Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein deploy clojars